/**
 * Generated by @rachelallyson/prisma-pothos-inputs. Do not edit.
 * Registers scalars, enums, and input types with your Pothos SchemaBuilder.
 * Input refs are typed as Prisma create/update inputs so you can pass args directly to Prisma.

 */

import type { Prisma } from '../../generated/prisma/client.js';
import type { InputTypeRef, ObjectRef } from '@pothos/core';

type BuilderTypes<B> = B extends PothosSchemaTypes.SchemaBuilder<infer T> ? T : never;

export function registerPothosTypes<B extends PothosSchemaTypes.SchemaBuilder<any>>(builder: B): {
  Role: ReturnType<B['enumType']>;
  SortOrder: ReturnType<B['enumType']>;
  BatchPayloadType: ObjectRef<BuilderTypes<B>, { count: number }>;
  UserOrderByInput: InputTypeRef<BuilderTypes<B>, Prisma.UserOrderByWithRelationInput>;
  PostOrderByInput: InputTypeRef<BuilderTypes<B>, Prisma.PostOrderByWithRelationInput>;
  UserWhereInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserWhereInput>;
  PostWhereInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostWhereInput>;
  UserFindManyArgs: InputTypeRef<BuilderTypes<B>, Prisma.UserFindManyArgs>;
  PostFindManyArgs: InputTypeRef<BuilderTypes<B>, Prisma.PostFindManyArgs>;
  UserWhereUniqueInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserWhereUniqueInput>;
  PostWhereUniqueInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostWhereUniqueInput>;
  UserCreateInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserCreateInput>;
  UserUpdateInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserUpdateInput>;
  PostCreateInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostCreateInput>;
  PostUpdateInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostUpdateInput>;
} {
  builder.scalarType('DateTime', {
    serialize: (d: unknown) => (d instanceof Date ? d : new Date(String(d))).toISOString(),
    parseValue: (v: unknown) => {
      if (typeof v === 'string' || typeof v === 'number') return new Date(v);
      throw new Error('DateTime must be a string or number');
    },
  });

  const Role = builder.enumType('Role', { values: ['USER', 'ADMIN'] satisfies readonly ['USER', 'ADMIN'] });

  const BatchPayloadType = builder.objectRef<{ count: number }>('BatchPayload').implement({
    fields: (t) => ({
      count: t.int({ resolve: (parent: { count: number }) => parent.count }),
    }),
  });

  const SortOrder = builder.enumType('SortOrder', { values: ['asc', 'desc'] satisfies readonly ['asc', 'desc'] });

  const UserOrderByInput = builder.inputType('UserOrderByInput', {
    fields: (t) => ({
      id: t.field({ type: SortOrder, required: false }),
      email: t.field({ type: SortOrder, required: false }),
      name: t.field({ type: SortOrder, required: false }),
      role: t.field({ type: SortOrder, required: false }),
      createdAt: t.field({ type: SortOrder, required: false }),
    }),
  });

  const PostOrderByInput = builder.inputType('PostOrderByInput', {
    fields: (t) => ({
      id: t.field({ type: SortOrder, required: false }),
      title: t.field({ type: SortOrder, required: false }),
      content: t.field({ type: SortOrder, required: false }),
      published: t.field({ type: SortOrder, required: false }),
      authorId: t.field({ type: SortOrder, required: false }),
    }),
  });

  // Scalar filters
  builder.inputType('StringFilter', {
    fields: (t) => ({
      equals: t.string({ required: false }),
      in: t.stringList({ required: false }),
      notIn: t.stringList({ required: false }),
      lt: t.string({ required: false }),
      lte: t.string({ required: false }),
      gt: t.string({ required: false }),
      gte: t.string({ required: false }),
      contains: t.string({ required: false }),
      startsWith: t.string({ required: false }),
      endsWith: t.string({ required: false }),
      not: t.field({ type: 'StringFilter', required: false }),
    }),
  });

  builder.inputType('StringNullableFilter', {
    fields: (t) => ({
      equals: t.string({ required: false }),
      in: t.stringList({ required: false }),
      notIn: t.stringList({ required: false }),
      lt: t.string({ required: false }),
      lte: t.string({ required: false }),
      gt: t.string({ required: false }),
      gte: t.string({ required: false }),
      contains: t.string({ required: false }),
      startsWith: t.string({ required: false }),
      endsWith: t.string({ required: false }),
      not: t.field({ type: 'StringNullableFilter', required: false }),
    }),
  });

  builder.inputType('IntFilter', {
    fields: (t) => ({
      equals: t.int({ required: false }),
      in: t.intList({ required: false }),
      notIn: t.intList({ required: false }),
      lt: t.int({ required: false }),
      lte: t.int({ required: false }),
      gt: t.int({ required: false }),
      gte: t.int({ required: false }),
      not: t.field({ type: 'IntFilter', required: false }),
    }),
  });

  builder.inputType('FloatFilter', {
    fields: (t) => ({
      equals: t.float({ required: false }),
      in: t.floatList({ required: false }),
      notIn: t.floatList({ required: false }),
      lt: t.float({ required: false }),
      lte: t.float({ required: false }),
      gt: t.float({ required: false }),
      gte: t.float({ required: false }),
      not: t.field({ type: 'FloatFilter', required: false }),
    }),
  });

  builder.inputType('BooleanFilter', {
    fields: (t) => ({
      equals: t.boolean({ required: false }),
      not: t.field({ type: 'BooleanFilter', required: false }),
    }),
  });

  builder.inputType('DateTimeFilter', {
    fields: (t) => ({
      equals: t.field({ type: 'DateTime', required: false }),
      in: t.field({ type: ['DateTime'], required: false }),
      notIn: t.field({ type: ['DateTime'], required: false }),
      lt: t.field({ type: 'DateTime', required: false }),
      lte: t.field({ type: 'DateTime', required: false }),
      gt: t.field({ type: 'DateTime', required: false }),
      gte: t.field({ type: 'DateTime', required: false }),
      not: t.field({ type: 'DateTimeFilter', required: false }),
    }),
  });

  builder.inputType('DateTimeNullableFilter', {
    fields: (t) => ({
      equals: t.field({ type: 'DateTime', required: false }),
      in: t.field({ type: ['DateTime'], required: false }),
      notIn: t.field({ type: ['DateTime'], required: false }),
      lt: t.field({ type: 'DateTime', required: false }),
      lte: t.field({ type: 'DateTime', required: false }),
      gt: t.field({ type: 'DateTime', required: false }),
      gte: t.field({ type: 'DateTime', required: false }),
      not: t.field({ type: 'DateTimeNullableFilter', required: false }),
    }),
  });

  const RoleFilter = builder.inputType('RoleFilter', {
    fields: (t) => ({
      equals: t.field({ type: Role, required: false }),
      in: t.field({ type: [Role], required: false }),
      notIn: t.field({ type: [Role], required: false }),
      not: t.field({ type: 'RoleFilter', required: false }),
    }),
  });

  builder.inputType('PostListRelationFilterInput', {
    fields: (t) => ({
      every: t.field({ type: 'PostWhereInput', required: false }),
      some: t.field({ type: 'PostWhereInput', required: false }),
      none: t.field({ type: 'PostWhereInput', required: false }),
    }),
  });

  builder.inputType('UserRelationFilterInput', {
    fields: (t) => ({
      is: t.field({ type: 'UserWhereInput', required: false }),
      isNot: t.field({ type: 'UserWhereInput', required: false }),
    }),
  });

  const UserWhereInputType = builder.inputType('UserWhereInput', {
    fields: (t) => ({
      AND: t.field({ type: ['UserWhereInput'], required: false }),
      OR: t.field({ type: ['UserWhereInput'], required: false }),
      NOT: t.field({ type: 'UserWhereInput', required: false }),
      id: t.field({ type: 'StringFilter', required: false }),
      email: t.field({ type: 'StringFilter', required: false }),
      name: t.field({ type: 'StringNullableFilter', required: false }),
      role: t.field({ type: 'RoleFilter', required: false }),
      createdAt: t.field({ type: 'DateTimeFilter', required: false }),
      posts: t.field({ type: 'PostListRelationFilterInput', required: false }),
    }),
  });

  const PostWhereInputType = builder.inputType('PostWhereInput', {
    fields: (t) => ({
      AND: t.field({ type: ['PostWhereInput'], required: false }),
      OR: t.field({ type: ['PostWhereInput'], required: false }),
      NOT: t.field({ type: 'PostWhereInput', required: false }),
      id: t.field({ type: 'StringFilter', required: false }),
      title: t.field({ type: 'StringFilter', required: false }),
      content: t.field({ type: 'StringNullableFilter', required: false }),
      published: t.field({ type: 'BooleanFilter', required: false }),
      authorId: t.field({ type: 'StringFilter', required: false }),
      author: t.field({ type: 'UserRelationFilterInput', required: false }),
    }),
  });

  const UserFindManyArgs = builder.inputType('UserFindManyArgs', {
    fields: (t) => ({
      where: t.field({ type: 'UserWhereInput', required: false }),
      orderBy: t.field({ type: 'UserOrderByInput', required: false }),
      skip: t.int({ required: false }),
      take: t.int({ required: false }),
    }),
  });

  const PostFindManyArgs = builder.inputType('PostFindManyArgs', {
    fields: (t) => ({
      where: t.field({ type: 'PostWhereInput', required: false }),
      orderBy: t.field({ type: 'PostOrderByInput', required: false }),
      skip: t.int({ required: false }),
      take: t.int({ required: false }),
    }),
  });

  builder.inputType('UserIdEmailCompoundUniqueInput', {
    fields: (t) => ({
      id: t.string({ required: true }),
      email: t.string({ required: true }),
    }),
  });

  const UserWhereUniqueInputType = builder.inputType('UserWhereUniqueInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      email: t.string({ required: false }),
      id_email: t.field({ type: 'UserIdEmailCompoundUniqueInput', required: false }),
      AND: t.field({ type: ['UserWhereInput'], required: false }),
      OR: t.field({ type: ['UserWhereInput'], required: false }),
      NOT: t.field({ type: 'UserWhereInput', required: false }),
      name: t.field({ type: 'StringNullableFilter', required: false }),
      role: t.field({ type: 'RoleFilter', required: false }),
      createdAt: t.field({ type: 'DateTimeFilter', required: false }),
      posts: t.field({ type: 'PostListRelationFilterInput', required: false }),
    }),
  });

  const PostWhereUniqueInputType = builder.inputType('PostWhereUniqueInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      AND: t.field({ type: ['PostWhereInput'], required: false }),
      OR: t.field({ type: ['PostWhereInput'], required: false }),
      NOT: t.field({ type: 'PostWhereInput', required: false }),
      title: t.field({ type: 'StringFilter', required: false }),
      content: t.field({ type: 'StringNullableFilter', required: false }),
      published: t.field({ type: 'BooleanFilter', required: false }),
      authorId: t.field({ type: 'StringFilter', required: false }),
      author: t.field({ type: 'UserRelationFilterInput', required: false }),
    }),
  });

  builder.inputType('PostCreateWithoutAuthorInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      title: t.string({ required: true }),
      content: t.string({ required: false }),
      published: t.boolean({ required: false }),
    }),
  });

  builder.inputType('PostCreateOrConnectWithoutAuthorInput', {
    fields: (t) => ({
      where: t.field({ type: 'PostWhereUniqueInput', required: true }),
      create: t.field({ type: 'PostCreateWithoutAuthorInput', required: true }),
    }),
  });

  builder.inputType('PostCreateNestedOneWithoutAuthorInput', {
    fields: (t) => ({
      connect: t.field({ type: 'PostWhereUniqueInput', required: false }),
      create: t.field({ type: 'PostCreateWithoutAuthorInput', required: false }),
      connectOrCreate: t.field({ type: 'PostCreateOrConnectWithoutAuthorInput', required: false }),
    }),
  });

  builder.inputType('PostCreateNestedManyWithoutAuthorInput', {
    fields: (t) => ({
      create: t.field({ type: ['PostCreateWithoutAuthorInput'], required: false }),
      connect: t.field({ type: ['PostWhereUniqueInput'], required: false }),
      connectOrCreate: t.field({ type: ['PostCreateOrConnectWithoutAuthorInput'], required: false }),
    }),
  });

  builder.inputType('UserCreateWithoutPostsInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      email: t.string({ required: true }),
      name: t.string({ required: false }),
      role: t.field({ type: Role, required: false }),
      createdAt: t.field({ type: 'DateTime', required: false }),
    }),
  });

  builder.inputType('UserCreateOrConnectWithoutPostsInput', {
    fields: (t) => ({
      where: t.field({ type: 'UserWhereUniqueInput', required: true }),
      create: t.field({ type: 'UserCreateWithoutPostsInput', required: true }),
    }),
  });

  builder.inputType('UserCreateNestedOneWithoutPostsInput', {
    fields: (t) => ({
      connect: t.field({ type: 'UserWhereUniqueInput', required: false }),
      create: t.field({ type: 'UserCreateWithoutPostsInput', required: false }),
      connectOrCreate: t.field({ type: 'UserCreateOrConnectWithoutPostsInput', required: false }),
    }),
  });

  builder.inputType('PostUpdateWithoutAuthorInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      title: t.string({ required: false }),
      content: t.string({ required: false }),
      published: t.boolean({ required: false }),
    }),
  });

  builder.inputType('PostUpdateOneWithoutAuthorNestedInput', {
    fields: (t) => ({
      connect: t.field({ type: 'PostWhereUniqueInput', required: false }),
      disconnect: t.field({ type: 'Boolean', required: false }),
      create: t.field({ type: 'PostCreateWithoutAuthorInput', required: false }),
      connectOrCreate: t.field({ type: 'PostCreateOrConnectWithoutAuthorInput', required: false }),
      update: t.field({ type: 'PostUpdateWithoutAuthorInput', required: false }),
    }),
  });

  builder.inputType('PostUpdateOneRequiredWithoutAuthorNestedInput', {
    fields: (t) => ({
      connect: t.field({ type: 'PostWhereUniqueInput', required: false }),
      disconnect: t.field({ type: 'Boolean', required: false }),
      create: t.field({ type: 'PostCreateWithoutAuthorInput', required: false }),
      connectOrCreate: t.field({ type: 'PostCreateOrConnectWithoutAuthorInput', required: false }),
      update: t.field({ type: 'PostUpdateWithoutAuthorInput', required: false }),
    }),
  });

  builder.inputType('PostUpdateWithWhereUniqueWithoutAuthorInput', {
    fields: (t) => ({
      where: t.field({ type: 'PostWhereUniqueInput', required: true }),
      data: t.field({ type: 'PostUpdateWithoutAuthorInput', required: true }),
    }),
  });

  builder.inputType('PostUpdateManyWithWhereWithoutAuthorInput', {
    fields: (t) => ({
      where: t.field({ type: 'PostWhereInput', required: true }),
      data: t.field({ type: 'PostUpdateWithoutAuthorInput', required: true }),
    }),
  });

  builder.inputType('PostUpdateManyWithoutAuthorNestedInput', {
    fields: (t) => ({
      create: t.field({ type: ['PostCreateWithoutAuthorInput'], required: false }),
      connect: t.field({ type: ['PostWhereUniqueInput'], required: false }),
      set: t.field({ type: ['PostWhereUniqueInput'], required: false }),
      disconnect: t.field({ type: ['PostWhereUniqueInput'], required: false }),
      delete: t.field({ type: ['PostWhereUniqueInput'], required: false }),
      update: t.field({ type: ['PostUpdateWithWhereUniqueWithoutAuthorInput'], required: false }),
      updateMany: t.field({ type: ['PostUpdateManyWithWhereWithoutAuthorInput'], required: false }),
      deleteMany: t.field({ type: ['PostWhereInput'], required: false }),
      connectOrCreate: t.field({ type: ['PostCreateOrConnectWithoutAuthorInput'], required: false }),
    }),
  });

  builder.inputType('UserUpdateWithoutPostsInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      email: t.string({ required: false }),
      name: t.string({ required: false }),
      role: t.field({ type: Role, required: false }),
      createdAt: t.field({ type: 'DateTime', required: false }),
    }),
  });

  builder.inputType('UserUpdateOneWithoutPostsNestedInput', {
    fields: (t) => ({
      connect: t.field({ type: 'UserWhereUniqueInput', required: false }),
      disconnect: t.field({ type: 'Boolean', required: false }),
      create: t.field({ type: 'UserCreateWithoutPostsInput', required: false }),
      connectOrCreate: t.field({ type: 'UserCreateOrConnectWithoutPostsInput', required: false }),
      update: t.field({ type: 'UserUpdateWithoutPostsInput', required: false }),
    }),
  });

  builder.inputType('UserUpdateOneRequiredWithoutPostsNestedInput', {
    fields: (t) => ({
      connect: t.field({ type: 'UserWhereUniqueInput', required: false }),
      disconnect: t.field({ type: 'Boolean', required: false }),
      create: t.field({ type: 'UserCreateWithoutPostsInput', required: false }),
      connectOrCreate: t.field({ type: 'UserCreateOrConnectWithoutPostsInput', required: false }),
      update: t.field({ type: 'UserUpdateWithoutPostsInput', required: false }),
    }),
  });

  const UserCreateInputType = builder.inputType('UserCreateInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      email: t.string({ required: true }),
      name: t.string({ required: false }),
      role: t.field({ type: Role, required: false }),
      createdAt: t.field({ type: 'DateTime', required: false }),
      posts: t.field({ type: 'PostCreateNestedManyWithoutAuthorInput', required: false }),
    }),
  });

  const UserUpdateInputType = builder.inputType('UserUpdateInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      email: t.string({ required: false }),
      name: t.string({ required: false }),
      role: t.field({ type: Role, required: false }),
      createdAt: t.field({ type: 'DateTime', required: false }),
      posts: t.field({ type: 'PostUpdateManyWithoutAuthorNestedInput', required: false }),
    }),
  });

  const PostCreateInputType = builder.inputType('PostCreateInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      title: t.string({ required: true }),
      content: t.string({ required: false }),
      published: t.boolean({ required: false }),
      author: t.field({ type: 'UserCreateNestedOneWithoutPostsInput', required: true }),
    }),
  });

  const PostUpdateInputType = builder.inputType('PostUpdateInput', {
    fields: (t) => ({
      id: t.string({ required: false }),
      title: t.string({ required: false }),
      content: t.string({ required: false }),
      published: t.boolean({ required: false }),
      author: t.field({ type: 'UserUpdateOneRequiredWithoutPostsNestedInput', required: false }),
    }),
  });

  return { Role, SortOrder, BatchPayloadType, UserOrderByInput, PostOrderByInput, UserWhereInputType, PostWhereInputType, UserFindManyArgs, PostFindManyArgs, UserWhereUniqueInputType, PostWhereUniqueInputType, UserCreateInputType, UserUpdateInputType, PostCreateInputType, PostUpdateInputType } as unknown as { Role: ReturnType<B['enumType']>; SortOrder: ReturnType<B['enumType']>; BatchPayloadType: ObjectRef<BuilderTypes<B>, { count: number }>; UserOrderByInput: InputTypeRef<BuilderTypes<B>, Prisma.UserOrderByWithRelationInput>; PostOrderByInput: InputTypeRef<BuilderTypes<B>, Prisma.PostOrderByWithRelationInput>; UserWhereInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserWhereInput>; PostWhereInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostWhereInput>; UserFindManyArgs: InputTypeRef<BuilderTypes<B>, Prisma.UserFindManyArgs>; PostFindManyArgs: InputTypeRef<BuilderTypes<B>, Prisma.PostFindManyArgs>; UserWhereUniqueInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserWhereUniqueInput>; PostWhereUniqueInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostWhereUniqueInput>; UserCreateInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserCreateInput>; UserUpdateInputType: InputTypeRef<BuilderTypes<B>, Prisma.UserUpdateInput>; PostCreateInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostCreateInput>; PostUpdateInputType: InputTypeRef<BuilderTypes<B>, Prisma.PostUpdateInput> };
}