/**
 * Generated by @rachelallyson/prisma-pothos-inputs. Do not edit.
 * Pothos enum types from your Prisma schema.
 */

export function registerPothosEnums<T>(builder: { enumType(name: string, opts: { values: readonly string[] }): T }): Record<string, T> {
  const Role = builder.enumType('Role', { values: ['USER', 'ADMIN'] as const });
  return { Role } as Record<string, T>;
}
