import type { NormalizedSchema } from './types.js';

/**
 * Type for the Pothos builder passed to registerPothosEnums.
 * Avoids a hard dependency on @pothos/core.
 */
export interface PothosEnumBuilder {
  enumType(name: string, opts: { values: readonly string[] }): unknown;
}

/**
 * Generates TypeScript source that exports registerPothosEnums(builder).
 * Call it with your SchemaBuilder to register all enums from the Prisma schema
 * and get back { [enumName]: enumTypeRef } for use in your Pothos schema.
 * Generated code is self-contained (no import from this package).
 */
export function generatePothosEnums(normalized: NormalizedSchema): string {
  const lines: string[] = [
    `/**`,
    ` * Generated by @rachelallyson/prisma-pothos-inputs. Do not edit.`,
    ` * Pothos enum types from your Prisma schema.`,
    ` */`,
    ``,
    `export function registerPothosEnums<T>(builder: { enumType(name: string, opts: { values: readonly string[] }): T }): Record<string, T> {`,
  ];

  for (const e of normalized.enums) {
    const valuesStr = e.values.map((v) => `'${v}'`).join(', ');
    lines.push(`  const ${e.name} = builder.enumType('${e.name}', { values: [${valuesStr}] as const });`);
  }

  if (normalized.enums.length > 0) {
    const returnKeys = normalized.enums.map((e) => e.name).join(', ');
    lines.push(`  return { ${returnKeys} } as Record<string, T>;`);
  } else {
    lines.push(`  return {} as Record<string, T>;`);
  }

  lines.push(`}`);

  return lines.join('\n');
}
