
import type { NormalizedSchema, NormalizedModel, NormalizedEnum, ModelField } from './types.js';
import { CUSTOM_SCALARS } from './types.js';

const INDENT = '  ';

/** Options for generatePothosSchema. */
export interface GeneratePothosSchemaOptions {
  /** Import path for Prisma namespace (e.g. '../../generated/prisma/client.js'). When set, returned input refs are typed as Prisma create/update inputs so you can pass args directly to Prisma. */
  prismaClientPath?: string;
  /** When true, CreateInput/UpdateInput include nested relation inputs (connect, create, connectOrCreate) instead of only scalar FKs. Typed as Prisma CreateInput/UpdateInput. */
  useRelationInputs?: boolean;
  /** When true, generates builder.prismaObject(modelName, { fields }) for each Prisma model so you don't have to wire object types by hand. Requires @pothos/plugin-prisma. */
  includePrismaObjects?: boolean;
  /** When true and includePrismaObjects is true, Json fields with a /// [TypeName] comment (prisma-json-types-generator) use that type name in Pothos so you can map to your namespace types. Register the type (e.g. builder.objectType('UserProfile', ...)) before calling registerPothosTypes. */
  usePrismaJsonTypes?: boolean;
}

/** Generates TypeScript that registers scalars, enums, and input types with a Pothos builder. */
export function generatePothosSchema(
  normalized: NormalizedSchema,
  options: GeneratePothosSchemaOptions = {}
): string {
  const { prismaClientPath, useRelationInputs = false, includePrismaObjects = false, usePrismaJsonTypes = false } = options;
  const enumRefs: string[] = [];
  const orderByRefs: string[] = [];
  const inputRefs: string[] = [];
  const objectRefs: string[] = [];
  /** Map input ref var name -> Prisma type name for Create/Update (e.g. UserCreateInputType -> 'UserCreateInput'). */
  const inputRefToPrismaType = new Map<string, string>();

  const lines: string[] = [
    `/**`,
    ` * Generated by @rachelallyson/prisma-pothos-inputs. Do not edit.`,
    ` * Registers scalars, enums, and input types with your Pothos SchemaBuilder.`,
    prismaClientPath ? ` * Input refs are typed as Prisma create/update inputs so you can pass args directly to Prisma.` : '',
    includePrismaObjects ? ` * Also registers Prisma object types (builder.prismaObject) for each model; requires @pothos/plugin-prisma.` : '',
    usePrismaJsonTypes ? ` * Json fields with /// [TypeName] use that Pothos type name (register it before calling registerPothosTypes).` : '',
    ` */`,
    ``,
  ];

  if (prismaClientPath) {
    lines.push(`import type { Prisma } from '${prismaClientPath}';`);
    lines.push(`import type { InputTypeRef, ObjectRef } from '@pothos/core';`);
    lines.push(``);
  }

  lines.push(`type BuilderTypes<B> = B extends PothosSchemaTypes.SchemaBuilder<infer T> ? T : never;`);
  lines.push(``);
  lines.push(
    `export function registerPothosTypes<B extends PothosSchemaTypes.SchemaBuilder<any>>(builder: B): {`
  );

  // Return type entries (inserted after "): {"
  // Scalars used by the schema (DateTime is common; others can be added)
  const scalarsToEmit = ['DateTime'];
  for (const name of scalarsToEmit) {
    if (!CUSTOM_SCALARS.includes(name as (typeof CUSTOM_SCALARS)[number])) continue;
    lines.push(`${INDENT}builder.scalarType('${name}', {`);
    if (name === 'DateTime') {
      lines.push(`${INDENT}  serialize: (d: unknown) => (d instanceof Date ? d : new Date(String(d))).toISOString(),`);
      lines.push(`${INDENT}  parseValue: (v: unknown) => {`);
      lines.push(`${INDENT}    if (typeof v === 'string' || typeof v === 'number') return new Date(v);`);
      lines.push(`${INDENT}    throw new Error('DateTime must be a string or number');`);
      lines.push(`${INDENT}  },`);
    } else {
      lines.push(`${INDENT}  serialize: (v) => v,`);
      lines.push(`${INDENT}  parseValue: (v) => v,`);
    }
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // Schema enums (e.g. Role)
  for (const e of normalized.enums) {
    const valuesStr = e.values.map((v) => `'${v}'`).join(', ');
    const varName = e.name;
    enumRefs.push(varName);
    lines.push(`${INDENT}const ${varName} = builder.enumType('${e.name}', { values: [${valuesStr}] satisfies readonly [${e.values.map((v) => `'${v}'`).join(', ')}] });`);
  }
  if (normalized.enums.length > 0) lines.push(``);

  // BatchPayload: return type for updateMany/deleteMany/createMany (not a Prisma model)
  objectRefs.push('BatchPayloadType');
  lines.push(`${INDENT}const BatchPayloadType = builder.objectRef<{ count: number }>('BatchPayload').implement({`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    count: t.int({ resolve: (parent: { count: number }) => parent.count, nullable: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);

  // SortOrder enum (asc/desc) and OrderBy input types per model — shape matches Prisma so orderBy can be passed through
  const modelsWithOrderBy = normalized.models.filter((m) =>
    m.fields.some((f) => f.kind === 'scalar' || f.kind === 'enum')
  );
  if (modelsWithOrderBy.length > 0) {
    enumRefs.push('SortOrder');
    lines.push(`${INDENT}const SortOrder = builder.enumType('SortOrder', { values: ['asc', 'desc'] satisfies readonly ['asc', 'desc'] });`);
    lines.push(``);
    for (const model of modelsWithOrderBy) {
      const sortable = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');
      const varName = `${model.name}OrderByInput`;
      orderByRefs.push(varName);
      inputRefs.push(varName);
      inputRefToPrismaType.set(varName, `${model.name}OrderByWithRelationInput`);
      lines.push(`${INDENT}const ${varName} = builder.inputType('${model.name}OrderByInput', {`);
      lines.push(`${INDENT}  fields: (t) => ({`);
      for (const f of sortable) {
        lines.push(`${INDENT}    ${f.name}: t.field({ type: SortOrder, required: false }),`);
      }
      lines.push(`${INDENT}  }),`);
      lines.push(`${INDENT}});`);
      lines.push(``);
    }
  }

  // Scalar filter input types (used by WhereInput)
  lines.push(`${INDENT}// Scalar filters`);
  for (const line of scalarFilterInputLines()) lines.push(line);
  lines.push(``);

  // Per-enum filter input types
  for (const e of normalized.enums) {
    const filterVarName = `${e.name}Filter`;
    lines.push(`${INDENT}const ${filterVarName} = builder.inputType('${e.name}Filter', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    lines.push(`${INDENT}    equals: t.field({ type: ${e.name}, required: false }),`);
    lines.push(`${INDENT}    in: t.field({ type: [${e.name}], required: false }),`);
    lines.push(`${INDENT}    notIn: t.field({ type: [${e.name}], required: false }),`);
    lines.push(`${INDENT}    not: t.field({ type: '${e.name}Filter', required: false }),`);
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // List relation filter input types (every/some/none: ModelWhereInput) for models that are the target of a list relation
  const listRelationTargets = new Set<string>();
  for (const model of normalized.models) {
    for (const f of model.fields) {
      if (f.kind === 'relation' && f.isList && f.relationTo) listRelationTargets.add(f.relationTo);
    }
  }
  for (const modelName of normalized.models.map((m) => m.name)) {
    if (!listRelationTargets.has(modelName)) continue;
    lines.push(`${INDENT}builder.inputType('${modelName}ListRelationFilterInput', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    lines.push(`${INDENT}    every: t.field({ type: '${modelName}WhereInput', required: false }),`);
    lines.push(`${INDENT}    some: t.field({ type: '${modelName}WhereInput', required: false }),`);
    lines.push(`${INDENT}    none: t.field({ type: '${modelName}WhereInput', required: false }),`);
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // Scalar relation filter input types (is/isNot: ModelWhereInput) for models that are the target of a non-list relation
  const scalarRelationTargets = new Set<string>();
  for (const model of normalized.models) {
    for (const f of model.fields) {
      if (f.kind === 'relation' && !f.isList && f.relationTo) scalarRelationTargets.add(f.relationTo);
    }
  }
  for (const modelName of normalized.models.map((m) => m.name)) {
    if (!scalarRelationTargets.has(modelName)) continue;
    lines.push(`${INDENT}builder.inputType('${modelName}RelationFilterInput', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    lines.push(`${INDENT}    is: t.field({ type: '${modelName}WhereInput', required: false }),`);
    lines.push(`${INDENT}    isNot: t.field({ type: '${modelName}WhereInput', required: false }),`);
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // WhereInput per model (AND, OR, NOT + scalar/enum filters + relation filters) — matches Prisma's WhereInput shape
  for (const model of normalized.models) {
    const scalarEnumFields = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');
    const relationFields = model.fields.filter((f) => f.kind === 'relation' && f.relationTo);
    if (scalarEnumFields.length === 0 && relationFields.length === 0) continue;
    const whereInputVarName = `${model.name}WhereInputType`;
    inputRefs.push(whereInputVarName);
    inputRefToPrismaType.set(whereInputVarName, `${model.name}WhereInput`);
    lines.push(`${INDENT}const ${whereInputVarName} = builder.inputType('${model.name}WhereInput', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    lines.push(`${INDENT}    AND: t.field({ type: ['${model.name}WhereInput'], required: false }),`);
    lines.push(`${INDENT}    OR: t.field({ type: ['${model.name}WhereInput'], required: false }),`);
    lines.push(`${INDENT}    NOT: t.field({ type: '${model.name}WhereInput', required: false }),`);
    for (const f of scalarEnumFields) {
      const filterType = filterTypeForField(f, normalized.enums);
      lines.push(`${INDENT}    ${f.name}: t.field({ type: '${filterType}', required: false }),`);
    }
    for (const f of relationFields) {
      const other = f.relationTo!;
      const filterType = f.isList ? `${other}ListRelationFilterInput` : `${other}RelationFilterInput`;
      lines.push(`${INDENT}    ${f.name}: t.field({ type: '${filterType}', required: false }),`);
    }
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // FindManyArgs per model: single input (where, orderBy?, skip, take) so resolvers can ...(args.input ?? {})
  const hasOrderBy = new Set(orderByRefs);
  for (const model of normalized.models) {
    const scalarEnumFields = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');
    const relationFields = model.fields.filter((f) => f.kind === 'relation' && f.relationTo);
    if (scalarEnumFields.length === 0 && relationFields.length === 0) continue;
    const varName = `${model.name}FindManyArgs`;
    inputRefs.push(varName);
    inputRefToPrismaType.set(varName, `${model.name}FindManyArgs`);
    lines.push(`${INDENT}const ${varName} = builder.inputType('${model.name}FindManyArgs', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    lines.push(`${INDENT}    where: t.field({ type: '${model.name}WhereInput', required: false }),`);
    if (hasOrderBy.has(`${model.name}OrderByInput`)) {
      lines.push(`${INDENT}    orderBy: t.field({ type: '${model.name}OrderByInput', required: false }),`);
    }
    lines.push(`${INDENT}    skip: t.int({ required: false }),`);
    lines.push(`${INDENT}    take: t.int({ required: false }),`);
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // Compound unique input types (e.g. UserIdEmailCompoundUniqueInput for @@unique([id, email]))
  for (const model of normalized.models) {
    const compoundUniques = model.compoundUniques ?? [];
    for (const cu of compoundUniques) {
      const typeName = `${model.name}${compoundKeyToPascalCase(cu.key)}CompoundUniqueInput`;
      lines.push(`${INDENT}builder.inputType('${typeName}', {`);
      lines.push(`${INDENT}  fields: (t) => ({`);
      for (const fieldName of cu.fields) {
        const f = model.fields.find((x) => x.name === fieldName);
        if (f) {
          // All fields in a compound unique are required in Prisma
          lines.push(`${INDENT}    ${pothosFieldLine(f, normalized.enums, false)}`);
        }
      }
      lines.push(`${INDENT}  }),`);
      lines.push(`${INDENT}});`);
      lines.push(``);
    }
  }

  // WhereUniqueInput per model: unique keys + compound uniques + AND, OR, NOT + same filter fields as WhereInput (matches Prisma)
  for (const model of normalized.models) {
    const uniqueFields = model.fields.filter(
      (f) => (f.kind === 'scalar' || f.kind === 'enum') && (f.isId === true || f.isUnique === true)
    );
    const compoundUniques = model.compoundUniques ?? [];
    if (uniqueFields.length === 0 && compoundUniques.length === 0) continue;
    const scalarEnumFields = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');
    const relationFields = model.fields.filter((f) => f.kind === 'relation' && f.relationTo);
    const whereInputName = `${model.name}WhereInput`;
    const whereUniqueVarName = `${model.name}WhereUniqueInputType`;
    inputRefs.push(whereUniqueVarName);
    inputRefToPrismaType.set(whereUniqueVarName, `${model.name}WhereUniqueInput`);
    lines.push(`${INDENT}const ${whereUniqueVarName} = builder.inputType('${model.name}WhereUniqueInput', {`);
    lines.push(`${INDENT}  fields: (t) => ({`);
    for (const f of uniqueFields) {
      lines.push(`${INDENT}    ${pothosFieldLine(f, normalized.enums, true)}`);
    }
    for (const cu of compoundUniques) {
      const typeName = `${model.name}${compoundKeyToPascalCase(cu.key)}CompoundUniqueInput`;
      lines.push(`${INDENT}    ${cu.key}: t.field({ type: '${typeName}', required: false }),`);
    }
    lines.push(`${INDENT}    AND: t.field({ type: ['${whereInputName}'], required: false }),`);
    lines.push(`${INDENT}    OR: t.field({ type: ['${whereInputName}'], required: false }),`);
    lines.push(`${INDENT}    NOT: t.field({ type: '${whereInputName}', required: false }),`);
    for (const f of scalarEnumFields) {
      if (uniqueFields.some((u) => u.name === f.name)) continue;
      const filterType = filterTypeForField(f, normalized.enums);
      lines.push(`${INDENT}    ${f.name}: t.field({ type: '${filterType}', required: false }),`);
    }
    for (const f of relationFields) {
      const other = f.relationTo!;
      const filterType = f.isList ? `${other}ListRelationFilterInput` : `${other}RelationFilterInput`;
      lines.push(`${INDENT}    ${f.name}: t.field({ type: '${filterType}', required: false }),`);
    }
    lines.push(`${INDENT}  }),`);
    lines.push(`${INDENT}});`);
    lines.push(``);
  }

  // When useRelationInputs: emit CreateWithoutX, CreateOrConnectWithoutX, CreateNestedOneWithoutX (connect, create, connectOrCreate)
  const createdWithoutKeys = new Set<string>();
  const createdNestedManyKeys = new Set<string>();
  if (useRelationInputs) {
    for (const model of normalized.models) {
      for (const f of model.fields) {
        if (f.kind !== 'relation' || !f.relationTo || !f.relationBackField) continue;
        const otherName = f.relationTo;
        const backPascal = relationBackFieldToPascal(f.relationBackField);
        const key = `${otherName}:${backPascal}`;
        if (createdWithoutKeys.has(key)) {
          // Key already emitted (e.g. from the "one" side). Still emit CreateNestedMany if this is the list side.
          if (f.isList && !createdNestedManyKeys.has(key)) {
            createdNestedManyKeys.add(key);
            const withoutTypeName = `${otherName}CreateWithout${backPascal}Input`;
            const connectOrCreateTypeName = `${otherName}CreateOrConnectWithout${backPascal}Input`;
            const nestedManyTypeName = `${otherName}CreateNestedManyWithout${backPascal}Input`;
            lines.push(`${INDENT}builder.inputType('${nestedManyTypeName}', {`);
            lines.push(`${INDENT}  fields: (t) => ({`);
            lines.push(`${INDENT}    create: t.field({ type: ['${withoutTypeName}'], required: false }),`);
            lines.push(`${INDENT}    connect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
            lines.push(`${INDENT}    connectOrCreate: t.field({ type: ['${connectOrCreateTypeName}'], required: false }),`);
            lines.push(`${INDENT}  }),`);
            lines.push(`${INDENT}});`);
            lines.push(``);
          }
          continue;
        }
        createdWithoutKeys.add(key);
        const otherModel = normalized.models.find((m) => m.name === otherName);
        if (!otherModel) continue;
        const otherScalars = otherModel.fields.filter((x) => x.kind === 'scalar' || x.kind === 'enum');
        // Exclude ALL relation key fields so CreateWithoutX uses nested relations (e.g. customField: { connect } not customFieldId).
        const allKeyFieldsToOmit = new Set<string>();
        const otherRelationFields = otherModel.fields.filter((ff) => ff.kind === 'relation' && ff.relationTo && ff.relationBackField);
        for (const orf of otherRelationFields) {
          for (const k of orf.relationKeyFields ?? []) allKeyFieldsToOmit.add(k);
        }
        const otherScalarsFiltered = otherScalars.filter((s) => !allKeyFieldsToOmit.has(s.name));
        const withoutFields = createInputFields(otherScalarsFiltered, normalized.enums);
        const withoutTypeName = `${otherName}CreateWithout${backPascal}Input`;
        lines.push(`${INDENT}builder.inputType('${withoutTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        for (const line of withoutFields) lines.push(`${INDENT}    ${line}`);
        for (const orf of otherRelationFields) {
          if (orf.relationTo === model.name && orf.relationBackField === f.name) continue;
          const relBackPascal = relationBackFieldToPascal(orf.relationBackField!);
          const nestedType = orf.isList
            ? `${orf.relationTo}CreateNestedManyWithout${relBackPascal}Input`
            : `${orf.relationTo}CreateNestedOneWithout${relBackPascal}Input`;
          lines.push(`${INDENT}    ${orf.name}: t.field({ type: '${nestedType}', required: ${!orf.optional && !orf.isList} }),`);
        }
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        const connectOrCreateTypeName = `${otherName}CreateOrConnectWithout${backPascal}Input`;
        lines.push(`${INDENT}builder.inputType('${connectOrCreateTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        lines.push(`${INDENT}    where: t.field({ type: '${otherName}WhereUniqueInput', required: true }),`);
        lines.push(`${INDENT}    create: t.field({ type: '${withoutTypeName}', required: true }),`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        const nestedOneTypeName = `${otherName}CreateNestedOneWithout${backPascal}Input`;
        lines.push(`${INDENT}builder.inputType('${nestedOneTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        lines.push(`${INDENT}    connect: t.field({ type: '${otherName}WhereUniqueInput', required: false }),`);
        lines.push(`${INDENT}    create: t.field({ type: '${withoutTypeName}', required: false }),`);
        lines.push(`${INDENT}    connectOrCreate: t.field({ type: '${connectOrCreateTypeName}', required: false }),`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        if (f.isList) {
          createdNestedManyKeys.add(key);
          const nestedManyTypeName = `${otherName}CreateNestedManyWithout${backPascal}Input`;
          lines.push(`${INDENT}builder.inputType('${nestedManyTypeName}', {`);
          lines.push(`${INDENT}  fields: (t) => ({`);
          lines.push(`${INDENT}    create: t.field({ type: ['${withoutTypeName}'], required: false }),`);
          lines.push(`${INDENT}    connect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
          lines.push(`${INDENT}    connectOrCreate: t.field({ type: ['${connectOrCreateTypeName}'], required: false }),`);
          lines.push(`${INDENT}  }),`);
          lines.push(`${INDENT}});`);
          lines.push(``);
        }
      }
    }
  }

  // When useRelationInputs: emit UpdateWithoutX, UpdateOneWithoutX, UpdateOneRequiredWithoutX, and for list UpdateManyWithoutX
  const updatedWithoutKeys = new Set<string>();
  const updatedNestedManyKeys = new Set<string>();
  if (useRelationInputs) {
    for (const model of normalized.models) {
      for (const f of model.fields) {
        if (f.kind !== 'relation' || !f.relationTo || !f.relationBackField) continue;
        const otherName = f.relationTo;
        const backPascal = relationBackFieldToPascal(f.relationBackField);
        const key = `${otherName}:${backPascal}`;
        if (updatedWithoutKeys.has(key)) {
          if (f.isList && !updatedNestedManyKeys.has(key)) {
            updatedNestedManyKeys.add(key);
            const updateWithoutTypeName = `${otherName}UpdateWithout${backPascal}Input`;
            const withoutTypeName = `${otherName}CreateWithout${backPascal}Input`;
            const connectOrCreateTypeName = `${otherName}CreateOrConnectWithout${backPascal}Input`;
            const updateWithWhereUniqueTypeName = `${otherName}UpdateWithWhereUniqueWithout${backPascal}Input`;
            const updateManyWithWhereTypeName = `${otherName}UpdateManyWithWhereWithout${backPascal}Input`;
            const nestedManyTypeName = `${otherName}UpdateManyWithout${backPascal}NestedInput`;
            lines.push(`${INDENT}builder.inputType('${updateWithWhereUniqueTypeName}', {`);
            lines.push(`${INDENT}  fields: (t) => ({`);
            lines.push(`${INDENT}    where: t.field({ type: '${otherName}WhereUniqueInput', required: true }),`);
            lines.push(`${INDENT}    data: t.field({ type: '${updateWithoutTypeName}', required: true }),`);
            lines.push(`${INDENT}  }),`);
            lines.push(`${INDENT}});`);
            lines.push(``);
            lines.push(`${INDENT}builder.inputType('${updateManyWithWhereTypeName}', {`);
            lines.push(`${INDENT}  fields: (t) => ({`);
            lines.push(`${INDENT}    where: t.field({ type: '${otherName}WhereInput', required: true }),`);
            lines.push(`${INDENT}    data: t.field({ type: '${updateWithoutTypeName}', required: true }),`);
            lines.push(`${INDENT}  }),`);
            lines.push(`${INDENT}});`);
            lines.push(``);
            lines.push(`${INDENT}builder.inputType('${nestedManyTypeName}', {`);
            lines.push(`${INDENT}  fields: (t) => ({`);
            lines.push(`${INDENT}    create: t.field({ type: ['${withoutTypeName}'], required: false }),`);
            lines.push(`${INDENT}    connect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
            lines.push(`${INDENT}    set: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
            lines.push(`${INDENT}    disconnect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
            lines.push(`${INDENT}    delete: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
            lines.push(`${INDENT}    update: t.field({ type: ['${updateWithWhereUniqueTypeName}'], required: false }),`);
            lines.push(`${INDENT}    updateMany: t.field({ type: ['${updateManyWithWhereTypeName}'], required: false }),`);
            lines.push(`${INDENT}    deleteMany: t.field({ type: ['${otherName}WhereInput'], required: false }),`);
            lines.push(`${INDENT}    connectOrCreate: t.field({ type: ['${connectOrCreateTypeName}'], required: false }),`);
            lines.push(`${INDENT}  }),`);
            lines.push(`${INDENT}});`);
            lines.push(``);
          }
          continue;
        }
        updatedWithoutKeys.add(key);
        const otherModel = normalized.models.find((m) => m.name === otherName);
        if (!otherModel) continue;
        const otherScalars = otherModel.fields.filter((x) => x.kind === 'scalar' || x.kind === 'enum');
        const otherRelationFields = otherModel.fields.filter((ff) => ff.kind === 'relation' && ff.relationTo && ff.relationBackField);
        const allKeyFieldsToOmit = new Set<string>();
        for (const orf of otherRelationFields) {
          for (const k of orf.relationKeyFields ?? []) allKeyFieldsToOmit.add(k);
        }
        const otherScalarsFiltered = otherScalars.filter((s) => !allKeyFieldsToOmit.has(s.name));
        const updateWithoutFields = updateInputFields(otherScalarsFiltered, normalized.enums);
        const updateWithoutTypeName = `${otherName}UpdateWithout${backPascal}Input`;
        lines.push(`${INDENT}builder.inputType('${updateWithoutTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        for (const line of updateWithoutFields) lines.push(`${INDENT}    ${line}`);
        for (const orf of otherRelationFields) {
          if (orf.relationTo === model.name && orf.relationBackField === f.name) continue;
          const relBackPascal = relationBackFieldToPascal(orf.relationBackField!);
          const nestedType = orf.isList
            ? `${orf.relationTo}UpdateManyWithout${relBackPascal}NestedInput`
            : orf.optional
              ? `${orf.relationTo}UpdateOneWithout${relBackPascal}NestedInput`
              : `${orf.relationTo}UpdateOneRequiredWithout${relBackPascal}NestedInput`;
          lines.push(`${INDENT}    ${orf.name}: t.field({ type: '${nestedType}', required: false }),`);
        }
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        const withoutTypeName = `${otherName}CreateWithout${backPascal}Input`;
        const connectOrCreateTypeName = `${otherName}CreateOrConnectWithout${backPascal}Input`;
        const nestedOneTypeName = `${otherName}CreateNestedOneWithout${backPascal}Input`;
        const updateOneTypeName = `${otherName}UpdateOneWithout${backPascal}NestedInput`;
        lines.push(`${INDENT}builder.inputType('${updateOneTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        lines.push(`${INDENT}    connect: t.field({ type: '${otherName}WhereUniqueInput', required: false }),`);
        lines.push(`${INDENT}    disconnect: t.field({ type: 'Boolean', required: false }),`);
        lines.push(`${INDENT}    create: t.field({ type: '${withoutTypeName}', required: false }),`);
        lines.push(`${INDENT}    connectOrCreate: t.field({ type: '${connectOrCreateTypeName}', required: false }),`);
        lines.push(`${INDENT}    update: t.field({ type: '${updateWithoutTypeName}', required: false }),`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        const updateOneRequiredTypeName = `${otherName}UpdateOneRequiredWithout${backPascal}NestedInput`;
        lines.push(`${INDENT}builder.inputType('${updateOneRequiredTypeName}', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        lines.push(`${INDENT}    connect: t.field({ type: '${otherName}WhereUniqueInput', required: false }),`);
        lines.push(`${INDENT}    disconnect: t.field({ type: 'Boolean', required: false }),`);
        lines.push(`${INDENT}    create: t.field({ type: '${withoutTypeName}', required: false }),`);
        lines.push(`${INDENT}    connectOrCreate: t.field({ type: '${connectOrCreateTypeName}', required: false }),`);
        lines.push(`${INDENT}    update: t.field({ type: '${updateWithoutTypeName}', required: false }),`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
        if (f.isList) {
          updatedNestedManyKeys.add(key);
          const updateWithWhereUniqueTypeName = `${otherName}UpdateWithWhereUniqueWithout${backPascal}Input`;
          lines.push(`${INDENT}builder.inputType('${updateWithWhereUniqueTypeName}', {`);
          lines.push(`${INDENT}  fields: (t) => ({`);
          lines.push(`${INDENT}    where: t.field({ type: '${otherName}WhereUniqueInput', required: true }),`);
          lines.push(`${INDENT}    data: t.field({ type: '${updateWithoutTypeName}', required: true }),`);
          lines.push(`${INDENT}  }),`);
          lines.push(`${INDENT}});`);
          lines.push(``);
          const updateManyWithWhereTypeName = `${otherName}UpdateManyWithWhereWithout${backPascal}Input`;
          lines.push(`${INDENT}builder.inputType('${updateManyWithWhereTypeName}', {`);
          lines.push(`${INDENT}  fields: (t) => ({`);
          lines.push(`${INDENT}    where: t.field({ type: '${otherName}WhereInput', required: true }),`);
          lines.push(`${INDENT}    data: t.field({ type: '${updateWithoutTypeName}', required: true }),`);
          lines.push(`${INDENT}  }),`);
          lines.push(`${INDENT}});`);
          lines.push(``);
          const nestedManyTypeName = `${otherName}UpdateManyWithout${backPascal}NestedInput`;
          lines.push(`${INDENT}builder.inputType('${nestedManyTypeName}', {`);
          lines.push(`${INDENT}  fields: (t) => ({`);
          lines.push(`${INDENT}    create: t.field({ type: ['${withoutTypeName}'], required: false }),`);
          lines.push(`${INDENT}    connect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
          lines.push(`${INDENT}    set: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
          lines.push(`${INDENT}    disconnect: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
          lines.push(`${INDENT}    delete: t.field({ type: ['${otherName}WhereUniqueInput'], required: false }),`);
          lines.push(`${INDENT}    update: t.field({ type: ['${updateWithWhereUniqueTypeName}'], required: false }),`);
          lines.push(`${INDENT}    updateMany: t.field({ type: ['${updateManyWithWhereTypeName}'], required: false }),`);
          lines.push(`${INDENT}    deleteMany: t.field({ type: ['${otherName}WhereInput'], required: false }),`);
          lines.push(`${INDENT}    connectOrCreate: t.field({ type: ['${connectOrCreateTypeName}'], required: false }),`);
          lines.push(`${INDENT}  }),`);
          lines.push(`${INDENT}});`);
          lines.push(``);
        }
      }
    }
  }

  // CreateInput and UpdateInput per model
  for (const model of normalized.models) {
    const scalarEnumFields = model.fields.filter((f) => f.kind === 'scalar' || f.kind === 'enum');
    const relationFields = model.fields.filter((f) => f.kind === 'relation' && f.relationTo && f.relationBackField);
    const fkFieldNames = new Set(
      relationFields.flatMap((f) => f.relationKeyFields ?? [])
    );

    if (useRelationInputs && relationFields.length > 0) {
      // Relation-style CreateInput: scalars except FKs + relation nested inputs. Type as CreateInput.
      const createScalars = scalarEnumFields.filter((f) => !fkFieldNames.has(f.name));
      const createFields = createInputFields(createScalars, normalized.enums);
      const createVarName = `${model.name}CreateInputType`;
      inputRefs.push(createVarName);
      inputRefToPrismaType.set(createVarName, `${model.name}CreateInput`);
      lines.push(`${INDENT}const ${createVarName} = builder.inputType('${model.name}CreateInput', {`);
      lines.push(`${INDENT}  fields: (t) => ({`);
      for (const line of createFields) lines.push(`${INDENT}    ${line}`);
      for (const f of relationFields) {
        const backPascal = relationBackFieldToPascal(f.relationBackField!);
        const nestedType = f.isList
          ? `${f.relationTo}CreateNestedManyWithout${backPascal}Input`
          : `${f.relationTo}CreateNestedOneWithout${backPascal}Input`;
        lines.push(`${INDENT}    ${f.name}: t.field({ type: '${nestedType}', required: ${!f.optional && !f.isList} }),`);
      }
      lines.push(`${INDENT}  }),`);
      lines.push(`${INDENT}});`);
      lines.push(``);
      // UpdateInput: scalars except FKs + relation nested inputs (UpdateOne/UpdateOneRequired/UpdateMany). Type as UpdateInput.
      const updateScalars = scalarEnumFields.filter((f) => !fkFieldNames.has(f.name));
      const updateFields = updateInputFields(updateScalars, normalized.enums);
      const updateVarName = `${model.name}UpdateInputType`;
      inputRefs.push(updateVarName);
      inputRefToPrismaType.set(updateVarName, `${model.name}UpdateInput`);
      lines.push(`${INDENT}const ${updateVarName} = builder.inputType('${model.name}UpdateInput', {`);
      lines.push(`${INDENT}  fields: (t) => ({`);
      for (const line of updateFields) lines.push(`${INDENT}    ${line}`);
      for (const f of relationFields) {
        const backPascal = relationBackFieldToPascal(f.relationBackField!);
        const nestedType = f.isList
          ? `${f.relationTo}UpdateManyWithout${backPascal}NestedInput`
          : f.optional
            ? `${f.relationTo}UpdateOneWithout${backPascal}NestedInput`
            : `${f.relationTo}UpdateOneRequiredWithout${backPascal}NestedInput`;
        lines.push(`${INDENT}    ${f.name}: t.field({ type: '${nestedType}', required: false }),`);
      }
      lines.push(`${INDENT}  }),`);
      lines.push(`${INDENT}});`);
      lines.push(``);
    } else {
      // Unchecked: scalar-only CreateInput/UpdateInput (current behavior)
      if (scalarEnumFields.length === 0) continue;

      const createFields = createInputFields(scalarEnumFields, normalized.enums);
      if (createFields.length > 0) {
        const createVarName = `${model.name}CreateInputType`;
        inputRefs.push(createVarName);
        const createPrismaType = `${model.name}UncheckedCreateInput`;
        inputRefToPrismaType.set(createVarName, createPrismaType);
        lines.push(`${INDENT}const ${createVarName} = builder.inputType('${model.name}CreateInput', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        for (const line of createFields) lines.push(`${INDENT}    ${line}`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
      }

      const updateFields = updateInputFields(scalarEnumFields, normalized.enums);
      if (updateFields.length > 0) {
        const updateVarName = `${model.name}UpdateInputType`;
        inputRefs.push(updateVarName);
        inputRefToPrismaType.set(updateVarName, `${model.name}UncheckedUpdateInput`);
        lines.push(`${INDENT}const ${updateVarName} = builder.inputType('${model.name}UpdateInput', {`);
        lines.push(`${INDENT}  fields: (t) => ({`);
        for (const line of updateFields) lines.push(`${INDENT}    ${line}`);
        lines.push(`${INDENT}  }),`);
        lines.push(`${INDENT}});`);
        lines.push(``);
      }
    }
  }

  // Optional: register Prisma object types (builder.prismaObject) for each model
  if (includePrismaObjects) {
    lines.push(`${INDENT}// Prisma object types (requires @pothos/plugin-prisma)`);
    lines.push(``);
    const modelsWithOrderBySet = new Set(
      normalized.models
        .filter((m) => m.fields.some((f) => f.kind === 'scalar' || f.kind === 'enum'))
        .map((m) => m.name)
    );
    for (const model of normalized.models) {
      lines.push(`${INDENT}builder.prismaObject('${model.name}', {`);
      lines.push(`${INDENT}  fields: (t) => ({`);
      for (const f of model.fields) {
        const fieldLines = prismaObjectFieldLines(f, modelsWithOrderBySet, usePrismaJsonTypes);
        for (const line of fieldLines) lines.push(`${INDENT}    ${line}`);
      }
      lines.push(`${INDENT}  }),`);
      lines.push(`${INDENT}});`);
      lines.push(``);
    }
  }

  const enumReturnType = `ReturnType<B['enumType']>`;
  /** When prismaClientPath is set we have ObjectRef import; use it so BatchPayloadType is properly typed and resolve inference works */
  const objectReturnType =
    prismaClientPath ? `ObjectRef<BuilderTypes<B>, { count: number }>` : `ReturnType<B['objectType']>`;
  const inputReturnType = (r: string) =>
    prismaClientPath && inputRefToPrismaType.has(r)
      ? `InputTypeRef<BuilderTypes<B>, Prisma.${inputRefToPrismaType.get(r)!}>`
      : `ReturnType<B['inputType']>`;
  const allRefs = [...enumRefs, ...objectRefs, ...inputRefs];
  const returnTypeLines = [
    ...enumRefs.map((r) => `  ${r}: ${enumReturnType};`),
    ...objectRefs.map((r) => `  ${r}: ${objectReturnType};`),
    ...inputRefs.map((r) => `  ${r}: ${inputReturnType(r)};`),
  ];
  const openSigIdx = lines.findIndex((l) => l.includes('(builder:'));
  const insertIdx = openSigIdx >= 0 ? openSigIdx + 1 : lines.length;
  lines.splice(insertIdx, 0, ...returnTypeLines, `} {`);
  const returnTypeStr = [
    ...enumRefs.map((r) => `${r}: ${enumReturnType}`),
    ...objectRefs.map((r) => `${r}: ${objectReturnType}`),
    ...inputRefs.map((r) => `${r}: ${inputReturnType(r)}`),
  ].join('; ');
  lines.push(`${INDENT}return { ${allRefs.join(', ')} } as unknown as { ${returnTypeStr} };`);
  lines.push(`}`);

  return lines.join('\n');
}

/** Returns one or more lines for a field in builder.prismaObject. List relations get where/orderBy/take/skip args so nested filters work. */
function prismaObjectFieldLines(
  f: ModelField,
  modelsWithOrderBy: Set<string>,
  usePrismaJsonTypes: boolean
): string[] {
  if (f.kind === 'relation') {
    const related = f.relationTo!;
    if (f.isList && related) {
      const orderByArg =
        modelsWithOrderBy.has(related)
          ? `orderBy: t.arg({ type: '${related}OrderByInput', required: false }),`
          : '';
      return [
        `${f.name}: t.relation('${f.name}', {`,
        `  onNull: 'error',`,
        `  nullable: false,`,
        `  args: {`,
        `    where: t.arg({ type: '${related}WhereInput', required: false }),`,
        orderByArg ? `    ${orderByArg}` : '',
        `    take: t.arg({ type: 'Int', required: false }),`,
        `    skip: t.arg({ type: 'Int', required: false }),`,
        `  },`,
        `  query: (args) => ({`,
        `    where: args.where ?? undefined,`,
        orderByArg ? `    orderBy: args.orderBy ?? undefined,` : '',
        `    take: args.take ?? undefined,`,
        `    skip: args.skip ?? undefined,`,
        `  }),`,
        `}),`,
      ].filter(Boolean);
    }
    const singleNullable = f.optional ? 'true' : 'false';
    return [`${f.name}: t.relation('${f.name}', { onNull: 'error', nullable: ${singleNullable} }),`];
  }
  const line = prismaObjectFieldLineScalarOrEnum(f, usePrismaJsonTypes);
  return [line];
}

/** Single-line field for scalars/enums (and single relations handled above). Object output: nullable only when the field is optional in the schema (can be null in DB), not when it merely has a default. Pothos v4+ defaults output fields to nullable, so we must set nullable: false for required fields. */
function prismaObjectFieldLineScalarOrEnum(f: ModelField, usePrismaJsonTypes: boolean): string {
  const nullable = f.optional;
  const nullOpt = nullable ? ', nullable: true' : ', nullable: false';
  const nullOptObj = nullable ? ', { nullable: true }' : ', { nullable: false }';
  if (f.kind === 'enum') {
    return `${f.name}: t.expose('${f.name}', { type: ${f.prismaType}${nullOpt} }),`;
  }
  switch (f.prismaType) {
    case 'String':
      return f.isId
        ? `${f.name}: t.exposeID('${f.name}', { nullable: false }),`
        : `${f.name}: t.exposeString('${f.name}'${nullOptObj}),`;
    case 'Int':
      return `${f.name}: t.exposeInt('${f.name}'${nullOptObj}),`;
    case 'Float':
      return `${f.name}: t.exposeFloat('${f.name}'${nullOptObj}),`;
    case 'Boolean':
      return `${f.name}: t.exposeBoolean('${f.name}'${nullOptObj}),`;
    case 'DateTime':
      return `${f.name}: t.expose('${f.name}', { type: 'DateTime'${nullOpt} }),`;
    case 'Json':
      const jsonType = usePrismaJsonTypes && f.jsonTypeRef ? f.jsonTypeRef : 'JSON';
      return `${f.name}: t.expose('${f.name}', { type: '${jsonType}'${nullOpt} }),`;
    case 'Bytes':
    case 'BigInt':
    case 'Decimal':
      return `${f.name}: t.expose('${f.name}', { type: '${f.prismaType}'${nullOpt} }),`;
    default:
      return `${f.name}: t.exposeString('${f.name}'${nullOptObj}),`;
  }
}

function createInputFields(fields: ModelField[], enums: NormalizedEnum[]): string[] {
  const out: string[] = [];
  for (const f of fields) {
    const optional = f.isId === true || f.optional || f.hasDefault === true;
    const line = pothosFieldLine(f, enums, optional);
    if (line) out.push(line);
  }
  return out;
}

function updateInputFields(fields: ModelField[], enums: NormalizedEnum[]): string[] {
  const out: string[] = [];
  for (const f of fields) {
    const line = pothosFieldLine(f, enums, true);
    if (line) out.push(line);
  }
  return out;
}

function pothosFieldLine(f: ModelField, _enums: NormalizedEnum[], optional: boolean): string {
  const req = optional ? 'false' : 'true';
  const prisma = f.prismaType;
  if (f.kind === 'enum') {
    return `${f.name}: t.field({ type: ${prisma}, required: ${req} }),`;
  }
  switch (prisma) {
    case 'String':
      return `${f.name}: t.string({ required: ${req} }),`;
    case 'Int':
      return `${f.name}: t.int({ required: ${req} }),`;
    case 'Float':
      return `${f.name}: t.float({ required: ${req} }),`;
    case 'Boolean':
      return `${f.name}: t.boolean({ required: ${req} }),`;
    case 'DateTime':
      return `${f.name}: t.field({ type: 'DateTime', required: ${req} }),`;
    case 'Json':
      return `${f.name}: t.field({ type: 'JSON', required: ${req} }),`;
    default:
      return `${f.name}: t.string({ required: ${req} }),`;
  }
}

/** Prisma compound unique type suffix: "id_email" -> "IdEmail" (for UserIdEmailCompoundUniqueInput). */
function compoundKeyToPascalCase(key: string): string {
  return key
    .split('_')
    .map((part) => (part.length > 0 ? part[0]!.toUpperCase() + part.slice(1).toLowerCase() : ''))
    .join('');
}

/** Prisma "WithoutX" suffix: "posts" -> "Posts" (for UserCreateWithoutPostsInput). */
function relationBackFieldToPascal(name: string): string {
  return name.length > 0 ? name[0]!.toUpperCase() + name.slice(1) : '';
}

/** Returns Pothos input type name for a field's filter (e.g. String -> 'StringFilter', optional String -> 'StringNullableFilter'). */
function filterTypeForField(f: ModelField, _enums: NormalizedEnum[]): string {
  if (f.kind === 'enum') return `${f.prismaType}Filter`;
  switch (f.prismaType) {
    case 'String':
      return f.optional ? 'StringNullableFilter' : 'StringFilter';
    case 'Int':
      return 'IntFilter';
    case 'Float':
      return 'FloatFilter';
    case 'Boolean':
      return 'BooleanFilter';
    case 'DateTime':
      return f.optional ? 'DateTimeNullableFilter' : 'DateTimeFilter';
    default:
      return f.optional ? 'StringNullableFilter' : 'StringFilter';
  }
}

/** Lines for scalar filter input types (StringFilter, IntFilter, BooleanFilter, DateTimeFilter, FloatFilter). */
function scalarFilterInputLines(): string[] {
  const lines: string[] = [];
  // StringFilter
  lines.push(`${INDENT}builder.inputType('StringFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.string({ required: false }),`);
  lines.push(`${INDENT}    in: t.stringList({ required: false }),`);
  lines.push(`${INDENT}    notIn: t.stringList({ required: false }),`);
  lines.push(`${INDENT}    lt: t.string({ required: false }),`);
  lines.push(`${INDENT}    lte: t.string({ required: false }),`);
  lines.push(`${INDENT}    gt: t.string({ required: false }),`);
  lines.push(`${INDENT}    gte: t.string({ required: false }),`);
  lines.push(`${INDENT}    contains: t.string({ required: false }),`);
  lines.push(`${INDENT}    startsWith: t.string({ required: false }),`);
  lines.push(`${INDENT}    endsWith: t.string({ required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'StringFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // StringNullableFilter (optional string fields)
  lines.push(`${INDENT}builder.inputType('StringNullableFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.string({ required: false }),`);
  lines.push(`${INDENT}    in: t.stringList({ required: false }),`);
  lines.push(`${INDENT}    notIn: t.stringList({ required: false }),`);
  lines.push(`${INDENT}    lt: t.string({ required: false }),`);
  lines.push(`${INDENT}    lte: t.string({ required: false }),`);
  lines.push(`${INDENT}    gt: t.string({ required: false }),`);
  lines.push(`${INDENT}    gte: t.string({ required: false }),`);
  lines.push(`${INDENT}    contains: t.string({ required: false }),`);
  lines.push(`${INDENT}    startsWith: t.string({ required: false }),`);
  lines.push(`${INDENT}    endsWith: t.string({ required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'StringNullableFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // IntFilter
  lines.push(`${INDENT}builder.inputType('IntFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.int({ required: false }),`);
  lines.push(`${INDENT}    in: t.intList({ required: false }),`);
  lines.push(`${INDENT}    notIn: t.intList({ required: false }),`);
  lines.push(`${INDENT}    lt: t.int({ required: false }),`);
  lines.push(`${INDENT}    lte: t.int({ required: false }),`);
  lines.push(`${INDENT}    gt: t.int({ required: false }),`);
  lines.push(`${INDENT}    gte: t.int({ required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'IntFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // FloatFilter
  lines.push(`${INDENT}builder.inputType('FloatFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.float({ required: false }),`);
  lines.push(`${INDENT}    in: t.floatList({ required: false }),`);
  lines.push(`${INDENT}    notIn: t.floatList({ required: false }),`);
  lines.push(`${INDENT}    lt: t.float({ required: false }),`);
  lines.push(`${INDENT}    lte: t.float({ required: false }),`);
  lines.push(`${INDENT}    gt: t.float({ required: false }),`);
  lines.push(`${INDENT}    gte: t.float({ required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'FloatFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // BooleanFilter
  lines.push(`${INDENT}builder.inputType('BooleanFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.boolean({ required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'BooleanFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // DateTimeFilter (required DateTime fields)
  lines.push(`${INDENT}builder.inputType('DateTimeFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    in: t.field({ type: ['DateTime'], required: false }),`);
  lines.push(`${INDENT}    notIn: t.field({ type: ['DateTime'], required: false }),`);
  lines.push(`${INDENT}    lt: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    lte: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    gt: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    gte: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'DateTimeFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  lines.push(``);
  // DateTimeNullableFilter (optional DateTime fields — allows equals: null for "where deletedAt is null")
  lines.push(`${INDENT}builder.inputType('DateTimeNullableFilter', {`);
  lines.push(`${INDENT}  fields: (t) => ({`);
  lines.push(`${INDENT}    equals: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    in: t.field({ type: ['DateTime'], required: false }),`);
  lines.push(`${INDENT}    notIn: t.field({ type: ['DateTime'], required: false }),`);
  lines.push(`${INDENT}    lt: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    lte: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    gt: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    gte: t.field({ type: 'DateTime', required: false }),`);
  lines.push(`${INDENT}    not: t.field({ type: 'DateTimeNullableFilter', required: false }),`);
  lines.push(`${INDENT}  }),`);
  lines.push(`${INDENT}});`);
  return lines;
}
